export const SET_ADS_REQUEST = "SET_ADS_REQUEST";
export const SET_ADS_SUCCESS = "SET_ADS_SUCCESS";
export const SET_ADS_ERROR = "SET_ADS_ERROR";

export const SET_AD_DETAIL_REQUEST = "SET_AD_DETAIL_REQUEST";
export const SET_AD_DETAIL_SUCCESS = "SET_AD_DETAIL_SUCCESS";
export const SET_AD_DETAIL_ERROR = "SET_AD_DETAIL_ERROR";

// export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
// export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
// export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

// export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
// export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
// export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

// export const USER_LOGOUT = "USER_LOGOUT";
