export const SET_ADS_REQUEST = "SET_ADS_REQUEST";
export const SET_ADS_SUCCESS = "SET_ADS_SUCCESS";
export const SET_ADS_ERROR = "SET_ADS_ERROR";

export const SET_AD_DETAIL_REQUEST = "SET_AD_DETAIL_REQUEST";
export const SET_AD_DETAIL_SUCCESS = "SET_AD_DETAIL_SUCCESS";
export const SET_AD_DETAIL_ERROR = "SET_AD_DETAIL_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
